In [6]:
#import important files and librabries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
#load data files

customers = pd.read_csv("../data/customers.csv")
orders = pd.read_csv("../data/orders.csv")
products = pd.read_csv("../data/products.csv")

In [8]:
customers.tail(1)

     customer_id customer_name gender  age       city    state signup_date
4999       C6000  Sakshi Verma   Male   24  Ahmedabad  Gujarat  2025-04-17

In [9]:

orders.tail(1)

,order_id,customer_id,product_id,order_date,quantity,sales,discount,profit
34999,O135000,C5976,P1288,2025-04-04,3,49781.95,5531.33,6929.07

In [10]:
products.tail(1)

    product_id product_name   category sub_category     price
299      P1300    Work Desk  Furniture        Desks  23696.07

In [11]:
customers.shape

(5000, 7)

In [12]:
orders.shape

(35000, 8)

In [13]:
products.shape

(300, 5)

In [14]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   str
 1   customer_name  5000 non-null   str
 2   gender         5000 non-null   str
 3   age            5000 non-null   int64
 4   city           5000 non-null   str
 5   state          5000 non-null   str
 6   signup_date    5000 non-null   str
dtypes: int64(1), str(6)
memory usage: 273.6 KB

In [15]:
print("Customers Missing Values : ")
print(customers.isnull().sum())

Customers Missing Values :
customer_id      0
customer_name    0
gender           0
age              0
city             0
state            0
signup_date      0
dtype: int64

In [16]:
print("Products missing value : ")
print(products.isnull().sum())

Products missing value :
product_id      0
product_name    0
category        0
sub_category    0
price           0
dtype: int64

In [17]:
print("Orders missing values : ")
print(orders.isnull().sum())

Orders missing values :
order_id       0
customer_id    0
product_id     0
order_date     0
quantity       0
sales          0
discount       0
profit         0
dtype: int64

In [18]:
# Check duplicate
print("Customers Duplicates:", customers.duplicated().sum())
print("Orders Duplicates:", orders.duplicated().sum())
print("Products Duplicates:", products.duplicated().sum())

Customers Duplicates: 0
Orders Duplicates: 0
Products Duplicates: 0

In [19]:
# Columns name as a list

print("Customers:", customers.columns.tolist())
print("Orders:", orders.columns.tolist())
print("Products:", products.columns.tolist())

Customers: ['customer_id', 'customer_name', 'gender', 'age', 'city', 'state', 'signup_date']
Orders: ['order_id', 'customer_id', 'product_id', 'order_date', 'quantity', 'sales', 'discount', 'profit']
Products: ['product_id', 'product_name', 'category', 'sub_category', 'price']

In [20]:
# Check duplicate base on id column
print("Duplicate Customer IDs:", customers["customer_id"].duplicated().sum())
print("Duplicate Order IDs:", orders["order_id"].duplicated().sum())
print("Duplicate Product IDs:", products["product_id"].duplicated().sum())

Duplicate Customer IDs: 0
Duplicate Order IDs: 0
Duplicate Product IDs: 0

In [21]:
# check data type 
print(customers.dtypes)
print("\n", orders.dtypes)
print("\n", products.dtypes)

customer_id        str
customer_name      str
gender             str
age              int64
city               str
state              str
signup_date        str
dtype: object

 order_id           str
customer_id        str
product_id         str
order_date         str
quantity         int64
sales          float64
discount       float64
profit         float64
dtype: object

 product_id          str
product_name        str
category            str
sub_category        str
price           float64
dtype: object

In [22]:
# datatype based on column 
print(customers["age"].dtypes)

int64

In [23]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [24]:
print(customers["signup_date"].dtype)
print(orders["order_date"].dtype)

datetime64[us]
datetime64[us]

In [25]:
# order products relationships
invalid_products = orders[
    ~orders["product_id"].isin(products["product_id"])
]

print("Invalid Product IDs:", len(invalid_products))

Invalid Product IDs: 0

In [26]:
# numeric data validation
print("Minimum Age:", customers["age"].min())
print("Maximum Age:", customers["age"].max())

Minimum Age: 18
Maximum Age: 65

In [27]:
print("Minimum Quantity:", orders["quantity"].min())

Minimum Quantity: 1

In [28]:
print("Minimum Sales:", orders["sales"].min())

Minimum Sales: 26.24

In [29]:
print("===== DATA QUALITY SUMMARY =====")

print("\nCustomers:")
print("Rows:", customers.shape[0])
print("Columns:", customers.shape[1])
print("Missing Values:", customers.isnull().sum().sum())
print("Duplicate Rows:", customers.duplicated().sum())
print("Duplicate IDs:", customers["customer_id"].duplicated().sum())

print("\nOrders:")
print("Rows:", orders.shape[0])
print("Columns:", orders.shape[1])
print("Missing Values:", orders.isnull().sum().sum())
print("Duplicate Rows:", orders.duplicated().sum())
print("Duplicate IDs:", orders["order_id"].duplicated().sum())

print("\nProducts:")
print("Rows:", products.shape[0])
print("Columns:", products.shape[1])
print("Missing Values:", products.isnull().sum().sum())
print("Duplicate Rows:", products.duplicated().sum())
print("Duplicate IDs:", products["product_id"].duplicated().sum())

===== DATA QUALITY SUMMARY =====

Customers:
Rows: 5000
Columns: 7
Missing Values: 0
Duplicate Rows: 0
Duplicate IDs: 0

Orders:
Rows: 35000
Columns: 8
Missing Values: 0
Duplicate Rows: 0
Duplicate IDs: 0

Products:
Rows: 300
Columns: 5
Missing Values: 0
Duplicate Rows: 0
Duplicate IDs: 0

In [30]:
print("Minimum Order Date:", orders["order_date"].min())
print("Maximum Order Date:", orders["order_date"].max())

Minimum Order Date: 2024-01-01 00:00:00
Maximum Order Date: 2025-12-30 00:00:00

In [31]:
print("Minimum Signup Date:", customers["signup_date"].min())
print("Maximum Signup Date:", customers["signup_date"].max())

Minimum Signup Date: 2023-01-01 00:00:00
Maximum Signup Date: 2025-12-30 00:00:00

In [32]:
print(
    "Future Order Dates:",
    (orders["order_date"] > pd.Timestamp.today()).sum()
)

Future Order Dates: 0

In [33]:
print(
    "Future Signup Dates:",
    (customers["signup_date"] > pd.Timestamp.today()).sum()
)

Future Signup Dates: 0

In [34]:
# Numerical Validation

In [35]:
print("Minimum Age:", customers["age"].min())
print("Maximum Age:", customers["age"].max())

Minimum Age: 18
Maximum Age: 65

In [36]:
print("Minimum Quantity:", orders["quantity"].min())
print("Maximum Quantity:", orders["quantity"].max())

Minimum Quantity: 1
Maximum Quantity: 5

In [37]:
print("Minimum Sales:", orders["sales"].min())
print("Maximum Sales:", orders["sales"].max())

Minimum Sales: 26.24
Maximum Sales: 515767.06

In [38]:
print("Minimum Profit:", orders["profit"].min())
print("Maximum Profit:", orders["profit"].max())

Minimum Profit: -41581.46
Maximum Profit: 75660.65

In [39]:
print("Minimum Discount:", orders["discount"].min())
print("Maximum Discount:", orders["discount"].max())

Minimum Discount: 0.0
Maximum Discount: 91562.29

In [40]:
print(orders["discount"].describe())

count    35000.000000
mean      2622.404620
std       5592.114863
min          0.000000
25%          0.000000
50%        266.350000
75%       2887.880000
max      91562.290000
Name: discount, dtype: float64

In [41]:
print(orders[["sales", "discount"]].sort_values(
    "discount", ascending=False
).head(10))

           sales  discount
33932  366249.16  91562.29
7558   351216.40  87804.10
10472  351216.40  87804.10
27474  351216.40  87804.10
28931  347464.13  86866.03
24091  319733.82  79933.46
14876  307410.40  76852.60
31383  283299.23  70824.81
1929   401251.26  70809.04
22243  376256.79  66398.26

In [42]:
print(
    "Discount greater than Sales:",
    (orders["discount"] > orders["sales"]).sum()
)

Discount greater than Sales: 0

In [43]:
print(
    "Negative Discount:",
    (orders["discount"] < 0).sum()
)

Negative Discount: 0

In [44]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [45]:
customers = customers.drop_duplicates()
orders = orders.drop_duplicates()
products = products.drop_duplicates()

In [46]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)

Customers: (5000, 7)
Orders: (35000, 8)
Products: (300, 5)

In [47]:
# save cleaned file

customers.to_csv("../data/cleaned_data/customers_clean.csv", index=False)
orders.to_csv("../data/cleaned_data/orders_clean.csv", index=False)
products.to_csv("../data/cleaned_data/products_clean.csv", index=False)

In [48]:
print("Clean datasets saved successfully!")

Clean datasets saved successfully!

In [49]:
# Now load cleand dataset for further operation
customers = pd.read_csv("../data/cleaned_data/customers_clean.csv")
orders = pd.read_csv("../data/cleaned_data/orders_clean.csv")
products = pd.read_csv("../data/cleaned_data/products_clean.csv")

In [50]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [51]:
orders["year"] = orders["order_date"].dt.year

In [52]:
orders["month"] = orders["order_date"].dt.month

In [53]:
orders["month_name"] = orders["order_date"].dt.month_name()

In [58]:
orders.head()

,order_id,customer_id,product_id,order_date,quantity,sales,discount,profit,year,month,month_name
0,O100001,C3457,P1061,2025-05-07,2,72620.80,0.00,10032.10,2025,5,May
1,O100002,C5242,P1274,2024-03-23,1,644.26,161.06,-60.90,2024,3,March
2,O100003,C4889,P1258,2025-08-01,2,874.78,97.20,75.35,2025,8,August
3,O100004,C2085,P1071,2024-07-18,2,27409.95,3045.55,3641.51,2024,7,July
4,O100005,C1265,P1132,2024-12-22,1,3540.92,393.44,396.32,2024,12,December

In [60]:
orders["net_sales"] = orders["sales"] - orders["discount"]

In [61]:
orders[[
    "order_date",
    "year",
    "month",
    "month_name",
    "sales",
    "discount",
    "net_sales"
]].head(10)

  order_date  year  month month_name     sales  discount  net_sales
0 2025-05-07  2025      5        May  72620.80      0.00   72620.80
1 2024-03-23  2024      3      March    644.26    161.06     483.20
2 2025-08-01  2025      8     August    874.78     97.20     777.58
3 2024-07-18  2024      7       July  27409.95   3045.55   24364.40
4 2024-12-22  2024     12   December   3540.92    393.44    3147.48
5 2024-01-09  2024      1    January   1470.50      0.00    1470.50
6 2024-01-13  2024      1    January  37143.39      0.00   37143.39
7 2025-07-30  2025      7       July  16669.58   1852.18   14817.40
8 2025-03-05  2025      3      March   1338.25      0.00    1338.25
9 2024-11-01  2024     11   November  83462.23   9273.58   74188.65

In [62]:
print("Minimum Net Sales:", orders["net_sales"].min())

Minimum Net Sales: 19.68

In [63]:
first_order = orders.groupby("customer_id")["order_date"].min().reset_index()

first_order.head()

  customer_id order_date
0       C1001 2024-05-20
1       C1002 2024-03-03
2       C1003 2024-02-08
3       C1004 2024-02-05
4       C1005 2024-02-03

In [64]:
customers = customers.merge(
    first_order,
    on="customer_id",
    how="left"
)

In [65]:
customers["days_to_first_order"] = (
    customers["order_date"] - customers["signup_date"]
).dt.days

In [66]:
customers[[
    "customer_id",
    "signup_date",
    "order_date",
    "days_to_first_order"
]].head(10)

  customer_id signup_date order_date  days_to_first_order
0       C1001  2025-09-12 2024-05-20               -480.0
1       C1002  2025-03-22 2024-03-03               -384.0
2       C1003  2023-08-15 2024-02-08                177.0
3       C1004  2025-12-26 2024-02-05               -690.0
4       C1005  2025-12-22 2024-02-03               -688.0
5       C1006  2023-02-14 2024-07-08                510.0
6       C1007  2023-01-29 2024-04-03                430.0
7       C1008  2023-09-26 2024-01-03                 99.0
8       C1009  2025-05-19 2024-06-24               -329.0
9       C1010  2024-10-16 2024-04-17               -182.0

In [67]:
print(
    "Orders before Signup:",
    (customers["days_to_first_order"] < 0).sum()
)

Orders before Signup: 2532

In [68]:
customers[customers["days_to_first_order"] < 0][[
    "customer_id",
    "signup_date",
    "order_date",
    "days_to_first_order"
]].head(10)

   customer_id signup_date order_date  days_to_first_order
0        C1001  2025-09-12 2024-05-20               -480.0
1        C1002  2025-03-22 2024-03-03               -384.0
3        C1004  2025-12-26 2024-02-05               -690.0
4        C1005  2025-12-22 2024-02-03               -688.0
8        C1009  2025-05-19 2024-06-24               -329.0
9        C1010  2024-10-16 2024-04-17               -182.0
10       C1011  2024-07-15 2024-01-16               -181.0
13       C1014  2024-11-29 2024-02-13               -290.0
15       C1016  2024-10-04 2024-05-30               -127.0
17       C1018  2025-05-12 2025-01-01               -131.0

In [69]:
print(
    "Minimum Days to First Order:",
    customers["days_to_first_order"].min()
)

Minimum Days to First Order: -726.0

In [70]:
print(
    "Maximum Days to First Order:",
    customers["days_to_first_order"].max()
)

Maximum Days to First Order: 989.0

In [71]:
customers.drop(
    columns=["order_date", "days_to_first_order"],
    inplace=True
)

In [72]:
customers.head()

  customer_id customer_name  gender  age       city          state signup_date
0       C1001     Amit Shah  Female   58   Siliguri    West Bengal  2025-09-12
1       C1002  Rohit Kapoor    Male   39  Bengaluru      Karnataka  2025-03-22
2       C1003   Rohit Gupta    Male   51  Faridabad        Haryana  2023-08-15
3       C1004    Mohit Jain  Female   64    Udaipur      Rajasthan  2025-12-26
4       C1005   Aditya Shah  Female   20    Lucknow  Uttar Pradesh  2025-12-22

In [73]:
customers.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'signup_date'],
      dtype='str')

In [74]:
#RFM Analysis(Recency, Frequency, Monetary)

In [75]:
analysis_date = orders["order_date"].max() + pd.Timedelta(days=1)
print("Analysis Date:", analysis_date)

Analysis Date: 2025-12-31 00:00:00

In [76]:
rfm = orders.groupby("customer_id").agg(
    Recency=("order_date", lambda x: (analysis_date - x.max()).days),
    Frequency=("order_id", "nunique"),
    Monetary=("net_sales", "sum")
).reset_index()

rfm.head()

  customer_id  Recency  Frequency   Monetary
0       C1001       56          6  236225.67
1       C1002       28         11  260935.80
2       C1003       32          3    4278.49
3       C1004       27         13  485127.79
4       C1005       91          5  251061.89

In [77]:
# RFM scoring

In [78]:
rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    5,
    labels=[5, 4, 3, 2, 1]
)

rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)

In [79]:
rfm.head(10)

  customer_id  Recency  Frequency   Monetary R_Score F_Score M_Score
0       C1001       56          6  236225.67       4       3       3
1       C1002       28         11  260935.80       4       4       4
2       C1003       32          3    4278.49       4       2       1
3       C1004       27         13  485127.79       4       5       5
4       C1005       91          5  251061.89       3       2       4
5       C1006      309          2  138663.78       1       1       3
6       C1007      162          4  194877.48       2       2       3
7       C1008      177          8  160191.06       2       4       3
8       C1009      356          2   49262.60       1       1       1
9       C1010       35          5   53690.15       4       2       2

In [81]:
# RFM Score Combine
# R = 4
# F = 5
# M = 5

In [82]:
rfm["RFM_Total"] = (
    rfm["R_Score"].astype(int)
    + rfm["F_Score"].astype(int)
    + rfm["M_Score"].astype(int)
)

rfm.head(10)

,customer_id,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Total
0,C1001,56,6,236225.67,4,3,3,10
1,C1002,28,11,260935.80,4,4,4,12
2,C1003,32,3,4278.49,4,2,1,7
3,C1004,27,13,485127.79,4,5,5,14
4,C1005,91,5,251061.89,3,2,4,9
5,C1006,309,2,138663.78,1,1,3,5
6,C1007,162,4,194877.48,2,2,3,7
7,C1008,177,8,160191.06,2,4,3,9
8,C1009,356,2,49262.60,1,1,1,3
9,C1010,35,5,53690.15,4,2,2,8

In [83]:
print("Minimum RFM Score:", rfm["RFM_Total"].min())
print("Maximum RFM Score:", rfm["RFM_Total"].max())

Minimum RFM Score: 3
Maximum RFM Score: 15

In [84]:
def segment_customer(row):

    R = int(row["R_Score"])
    F = int(row["F_Score"])
    M = int(row["M_Score"])

    if R >= 4 and F >= 4 and M >= 4:
        return "Champions"

    elif R >= 3 and F >= 4 and M >= 3:
        return "Loyal Customers"

    elif R >= 4 and 2 <= F <= 3 and M >= 2:
        return "Potential Loyalists"

    elif R >= 4 and F == 1 and M >= 1:
        return "New Customers"

    elif R <= 2 and F >= 4 and M >= 4:
        return "Can't Lose Them"

    elif R <= 2 and F >= 3 and M >= 3:
        return "At Risk"

    elif R <= 2 and F <= 2 and M <= 2:
        return "Hibernating"

    elif R == 1 and F == 1 and M == 1:
        return "Lost Customers"

    else:
        return "Others"

In [85]:
rfm["Segment"] = rfm.apply(segment_customer, axis=1)

In [86]:
rfm.head(10)

,customer_id,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Total,Segment
0,C1001,56,6,236225.67,4,3,3,10,Potential Loyalists
1,C1002,28,11,260935.80,4,4,4,12,Champions
2,C1003,32,3,4278.49,4,2,1,7,Others
3,C1004,27,13,485127.79,4,5,5,14,Champions
4,C1005,91,5,251061.89,3,2,4,9,Others
5,C1006,309,2,138663.78,1,1,3,5,Others
6,C1007,162,4,194877.48,2,2,3,7,Others
7,C1008,177,8,160191.06,2,4,3,9,At Risk
8,C1009,356,2,49262.60,1,1,1,3,Hibernating
9,C1010,35,5,53690.15,4,2,2,8,Potential Loyalists

In [87]:
rfm["Segment"].value_counts()

Segment
Hibernating            1025
Others                  973
Champions               957
Loyal Customers         576
Potential Loyalists     507
At Risk                 283
Can't Lose Them         166
New Customers           103
Name: count, dtype: int64

In [88]:
rfm[rfm["Segment"] == "Others"][[
    "customer_id",
    "Recency",
    "Frequency",
    "Monetary",
    "R_Score",
    "F_Score",
    "M_Score"
]].head(20)

   customer_id  Recency  Frequency   Monetary R_Score F_Score M_Score
2        C1003       32          3    4278.49       4       2       1
4        C1005       91          5  251061.89       3       2       4
5        C1006      309          2  138663.78       1       1       3
6        C1007      162          4  194877.48       2       2       3
11       C1012       74          3  166887.05       3       2       3
16       C1018      364          1  133543.64       1       1       3
17       C1019       89          3   53583.64       3       2       2
24       C1026      111          5   37362.54       3       2       1
40       C1042      186          3  235171.55       2       2       3
41       C1043      131          2  145772.92       2       1       3
42       C1044       80          2   88682.08       3       1       2
46       C1049      108          7  233602.13       3       3       3
51       C1055       97          6   57616.00       3       3       2
53       C1057      151          2  233007.37       2       1       3
54       C1058      112          4   89101.17       3       2       2
55       C1059       18          5   42463.73       5       2       1
70       C1075      534          3  136940.30       1       2       3
71       C1077      120          6   68270.54       2       3       2
72       C1078       13          5   26322.86       5       2       1
77       C1084       88          4   65288.60       3       2       2

In [89]:
rfm[rfm["Segment"] == "Others"][
    ["R_Score", "F_Score", "M_Score"]
].value_counts().head(20)

R_Score  F_Score  M_Score
3        3        3          87
         2        2          69
         1        1          63
         3        4          62
2        3        2          59
         2        3          58
1        2        3          57
3        3        2          52
1        3        2          42
         1        3          41
3        2        3          40
                  1          38
5        2        1          27
3        1        2          25
4        2        1          23
1        2        4          18
2        1        3          18
4        4        2          17
5        4        2          17
3        2        4          15
Name: count, dtype: int64

In [90]:
def segment_customer(row):

    R = int(row["R_Score"])
    F = int(row["F_Score"])
    M = int(row["M_Score"])

    # 1. Champions
    if R >= 4 and F >= 4 and M >= 4:
        return "Champions"

    # 2. Can't Lose Them
    elif R <= 2 and F >= 4 and M >= 4:
        return "Can't Lose Them"

    # 3. Loyal Customers
    elif R >= 3 and F >= 3 and M >= 3:
        return "Loyal Customers"

    # 4. At Risk
    elif R <= 2 and F >= 3 and M >= 3:
        return "At Risk"

    # 5. Hibernating
    elif R <= 2 and F <= 2 and M <= 2:
        return "Hibernating"

    # 6. Lost Customers
    elif R == 1 and F <= 2 and M <= 2:
        return "Lost Customers"

    # 7. New Customers
    elif R >= 4 and F <= 2:
        return "New Customers"

    # 8. Potential Loyalists
    elif R >= 3 and F <= 3:
        return "Potential Loyalists"

    # Remaining customers
    else:
        return "At Risk"

In [91]:
rfm["Segment"] = rfm.apply(segment_customer, axis=1)

In [92]:
rfm["Segment"].value_counts()

Segment
Hibernating            1025
Loyal Customers         983
Champions               957
At Risk                 699
Potential Loyalists     436
New Customers           324
Can't Lose Them         166
Name: count, dtype: int64

In [93]:
print("Total Customers:", len(rfm))
print("Total Segmented Customers:", rfm["Segment"].notna().sum())

Total Customers: 4590
Total Segmented Customers: 4590

In [94]:
customers_without_orders = customers[
    ~customers["customer_id"].isin(rfm["customer_id"])
]

print("Customers Without Orders:", len(customers_without_orders))

Customers Without Orders: 410

In [95]:
customers_without_orders.head(10)

,customer_id,customer_name,gender,age,city,state,signup_date
14,C1015,Priya Kapoor,Female,18,Mangaluru,Karnataka,2023-03-11
47,C1048,Karan Singh,Male,38,Nashik,Maharashtra,2023-01-20
49,C1050,Shreya Sharma,Male,59,Varanasi,Uttar Pradesh,2025-07-24
73,C1074,Divya Agarwal,Male,52,Aurangabad,Maharashtra,2024-03-18
75,C1076,Komal Chauhan,Male,27,Pune,Maharashtra,2024-01-29
78,C1079,Sneha Sharma,Male,22,Salem,Tamil Nadu,2023-06-28
130,C1131,Priya Shah,Male,39,Pune,Maharashtra,2024-11-13
157,C1158,Aditya Bansal,Female,47,Jodhpur,Rajasthan,2025-02-17
166,C1167,Vikas Bansal,Male,18,Hyderabad,Telangana,2023-09-10
192,C1193,Rahul Jain,Female,59,Noida,Uttar Pradesh,2025-07-16

In [96]:
print("Customers Without Orders:", len(customers_without_orders))

Customers Without Orders: 410

In [97]:
customers_without_orders.head(10)

,customer_id,customer_name,gender,age,city,state,signup_date
14,C1015,Priya Kapoor,Female,18,Mangaluru,Karnataka,2023-03-11
47,C1048,Karan Singh,Male,38,Nashik,Maharashtra,2023-01-20
49,C1050,Shreya Sharma,Male,59,Varanasi,Uttar Pradesh,2025-07-24
73,C1074,Divya Agarwal,Male,52,Aurangabad,Maharashtra,2024-03-18
75,C1076,Komal Chauhan,Male,27,Pune,Maharashtra,2024-01-29
78,C1079,Sneha Sharma,Male,22,Salem,Tamil Nadu,2023-06-28
130,C1131,Priya Shah,Male,39,Pune,Maharashtra,2024-11-13
157,C1158,Aditya Bansal,Female,47,Jodhpur,Rajasthan,2025-02-17
166,C1167,Vikas Bansal,Male,18,Hyderabad,Telangana,2023-09-10
192,C1193,Rahul Jain,Female,59,Noida,Uttar Pradesh,2025-07-16

In [98]:
customer360 = customers.merge(
    rfm[[
        "customer_id",
        "Recency",
        "Frequency",
        "Monetary",
        "R_Score",
        "F_Score",
        "M_Score",
        "RFM_Score",
        "RFM_Total",
        "Segment"
    ]],
    on="customer_id",
    how="left"
)

KeyError: "['RFM_Score'] not in index"

In [99]:
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str)
    + rfm["F_Score"].astype(str)
    + rfm["M_Score"].astype(str)
)

rfm["RFM_Total"] = (
    rfm["R_Score"].astype(int)
    + rfm["F_Score"].astype(int)
    + rfm["M_Score"].astype(int)
)

In [100]:
rfm.columns

Index(['customer_id', 'Recency', 'Frequency', 'Monetary', 'R_Score', 'F_Score',
       'M_Score', 'RFM_Total', 'Segment', 'RFM_Score'],
      dtype='str')

In [101]:
customer360 = customers.merge(
    rfm[
        [
            "customer_id",
            "Recency",
            "Frequency",
            "Monetary",
            "R_Score",
            "F_Score",
            "M_Score",
            "RFM_Score",
            "RFM_Total",
            "Segment"
        ]
    ],
    on="customer_id",
    how="left"
)

customer360["Segment"] = customer360["Segment"].fillna("No Purchase")

In [102]:
print("Total Customers:", len(customer360))
print("\nSegment Distribution:")
print(customer360["Segment"].value_counts())

Total Customers: 5000

Segment Distribution:
Segment
Hibernating            1025
Loyal Customers         983
Champions               957
At Risk                 699
Potential Loyalists     436
No Purchase             410
New Customers           324
Can't Lose Them         166
Name: count, dtype: int64

In [103]:
print(customer360.shape)
print(customer360["Segment"].value_counts())

(5000, 16)
Segment
Hibernating            1025
Loyal Customers         983
Champions               957
At Risk                 699
Potential Loyalists     436
No Purchase             410
New Customers           324
Can't Lose Them         166
Name: count, dtype: int64

In [104]:
customer360.head()

,customer_id,customer_name,gender,age,city,state,signup_date,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,RFM_Total,Segment
0,C1001,Amit Shah,Female,58,Siliguri,West Bengal,2025-09-12,56.0,6.0,236225.67,4,3,3,433,10.0,Loyal Customers
1,C1002,Rohit Kapoor,Male,39,Bengaluru,Karnataka,2025-03-22,28.0,11.0,260935.80,4,4,4,444,12.0,Champions
2,C1003,Rohit Gupta,Male,51,Faridabad,Haryana,2023-08-15,32.0,3.0,4278.49,4,2,1,421,7.0,New Customers
3,C1004,Mohit Jain,Female,64,Udaipur,Rajasthan,2025-12-26,27.0,13.0,485127.79,4,5,5,455,14.0,Champions
4,C1005,Aditya Shah,Female,20,Lucknow,Uttar Pradesh,2025-12-22,91.0,5.0,251061.89,3,2,4,324,9.0,Potential Loyalists

In [105]:
customer360.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   str
 1   customer_name  5000 non-null   str
 2   gender         5000 non-null   str
 3   age            5000 non-null   int64
 4   city           5000 non-null   str
 5   state          5000 non-null   str
 6   signup_date    5000 non-null   datetime64[us]
 7   Recency        4590 non-null   float64
 8   Frequency      4590 non-null   float64
 9   Monetary       4590 non-null   float64
 10  R_Score        4590 non-null   category
 11  F_Score        4590 non-null   category
 12  M_Score        4590 non-null   category
 13  RFM_Score      4590 non-null   str
 14  RFM_Total      4590 non-null   float64
 15  Segment        5000 non-null   str
dtypes: category(3), datetime64[us](1), float64(4), int64(1), str(7)
memory usage: 523.2 KB

In [106]:
customer360["Recency"] = customer360["Recency"].astype("Int64")
customer360["Frequency"] = customer360["Frequency"].astype("Int64")
customer360["RFM_Total"] = customer360["RFM_Total"].astype("Int64")

In [107]:
customer360.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   str
 1   customer_name  5000 non-null   str
 2   gender         5000 non-null   str
 3   age            5000 non-null   int64
 4   city           5000 non-null   str
 5   state          5000 non-null   str
 6   signup_date    5000 non-null   datetime64[us]
 7   Recency        4590 non-null   Int64
 8   Frequency      4590 non-null   Int64
 9   Monetary       4590 non-null   float64
 10  R_Score        4590 non-null   category
 11  F_Score        4590 non-null   category
 12  M_Score        4590 non-null   category
 13  RFM_Score      4590 non-null   str
 14  RFM_Total      4590 non-null   Int64
 15  Segment        5000 non-null   str
dtypes: Int64(3), category(3), datetime64[us](1), float64(1), int64(1), str(7)
memory usage: 537.9 KB

In [108]:
customer360["Purchase_Status"] = customer360["Segment"].apply(
    lambda x: "No Purchase" if x == "No Purchase" else "Purchased"
)

In [109]:
print(customer360["Purchase_Status"].value_counts())

Purchase_Status
Purchased      4590
No Purchase     410
Name: count, dtype: int64

In [110]:
print("Total Customers:", len(customer360))
print("Total Columns:", len(customer360.columns))

Total Customers: 5000
Total Columns: 17

In [111]:
customer360.to_csv(
    "../data/cleaned_data/customer360_final.csv",
    index=False
)

In [112]:
print("Customer360 final dataset saved successfully!")

Customer360 final dataset saved successfully!

In [113]:
pd.read_csv("../data/cleaned_data/customer360_final.csv").shape

(5000, 17)

In [115]:
customer360[customer360["Purchase_Status"] == "No Purchase"].head()

,customer_id,customer_name,gender,age,city,state,signup_date,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,RFM_Total,Segment,Purchase_Status
14,C1015,Priya Kapoor,Female,18,Mangaluru,Karnataka,2023-03-11,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,No Purchase,No Purchase
47,C1048,Karan Singh,Male,38,Nashik,Maharashtra,2023-01-20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,No Purchase,No Purchase
49,C1050,Shreya Sharma,Male,59,Varanasi,Uttar Pradesh,2025-07-24,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,No Purchase,No Purchase
73,C1074,Divya Agarwal,Male,52,Aurangabad,Maharashtra,2024-03-18,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,No Purchase,No Purchase
75,C1076,Komal Chauhan,Male,27,Pune,Maharashtra,2024-01-29,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,No Purchase,No Purchase

In [116]:
customer360[customer360["Purchase_Status"] == "No Purchase"].shape

(410, 17)

In [114]:
# Now load the data in mysql and apply analytics on this data

In [120]:
customer360.to_csv(
    "../data/cleaned_data/customer360_final_v2.csv",
    index=False,
    na_rep=""
)

In [121]:
pd.read_csv(
    "../data/cleaned_data/customer360_final_v2.csv"
).shape

(5000, 17)